### ISSUE TITLE
SolidusMailchimpSync::Error: 400: Bad Request

### ISSUE THREAD

**Issue by OndrejKu** [friendsoftheweb/solidus_mailchimp_sync#3]
Hi guys, 
I've installed your gem and run the sync. I got this error after synchronizing images: 

```
SolidusMailchimpSync::Error: 400: Bad Request: A product with the provided ID does not exist in the account for this list.
````
Should this gem create products in MC API, automatically? Any ideas how to fix it?

**Comment by joshhepworth** [comment]
You'll want to run the rake task `solidus_mailchimp_sync:bulk_sync` from your production environment to add products and such to Mailchimp. If you have a lot it might take a while to run.

As a heads up, we're not actively developing this gem anymore, but would be happy to review and accept pull requests if you find issues.

**Comment by OndrejKu** [comment]
@joshhepworth that was exactly the command I used for synchronizing products for the first time.
